name: Fetch & Clean Victoria ICS

on:
  schedule:
    - cron: "15 0 * * *"   # 每天 00:15 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  fetch-clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests icalendar

      - name: Run cleaner
        run: |
          python victoria_ics.py
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ics): fetch & clean Victoria ICS"
          file_pattern: victoria.cleaned.ics
      
